### ISSUE TITLE
how to set up the environments

### ISSUE THREAD

**Issue by zhavgyating** [aubombarely/Organelle_PBA#10]
how to do this step?
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/42016831/43562187-e78a7294-95cf-11e8-9e53-6286ffe30ce8.png">

**Comment by aubombarely** [comment]
You need to do this step if the executables are not in the PATH. For example, if you download Sprai and you install it in /home/username/sprai, you'll need to run the command "export SPRAI_PATH=/home/username/sprai", so the script will be able to find the programs that need to run the assembly.
