### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by smoretti** [aubombarely/Organelle_PBA#18]
Hi
what is the license used to distribute Organelle_PBA?

Best

**Comment by aubombarely** [comment]
Hi Smoretti, 

  I guess that it should be GNU Public License. You are free to use, modify and distribute with no restrictions except that any new software derived from this code, should have the GNU Public License (I think). If you use the software in your research, we are always thankful if you can cite the article associated with this code (Soorni et. al 2017)(https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3412-9).

Let me know if you have any other question, 

Best regards

Aure

**Comment by smoretti** [comment]
OK, thanks
