### ISSUE TITLE
ERROR: Sprai/CA didnt produced an output 9-terminator. Check log.

### ISSUE THREAD

**Issue by diriano** [aubombarely/Organelle_PBA#2]
Hi,

I am trying to use your software with the test data. First I had  a problem with BLASR (I ma using BLASR that comes with the installation of FALCON-integrate), but I think I solved that: https://github.com/aubombarely/Organelle_PBA/issues/1

Now the script stops during Sprai with the message:
ERROR: Sprai/CA didnt produced an output 9-terminator. Check log.

Looking at 02_1_Sprai_log.txt, it seems it is looking for a script that does not exists:
sh: /data1/bioinfo/sprai-0.9.1/bin/ezez_vx1.pl: No such file or directory

I ma using sprai v0.9.1. It was the only version that I found. The site http://zombie.cb.k.u-tokyo.ac.jp/sprai/README.html is not responding.

I will greatly appreciate any help you can provide to solve this and then be able to run your software with the test dataset.

Looking forward to your reply!

Cheers,
Diego

**Comment by agroppi** [comment]
@diriano 
I'm using `sprai-0.9.9.23.tar.gz`
`sprai/bin/ezez_vx1.pl` exists in this version of Sprai

**Comment by diriano** [comment]
The site http://zombie.cb.k.u-tokyo.ac.jp/sprai/README.html is back online. I have installed sprai 0.9.9.23 and I am running the pipeline with the test data.

**Comment by diriano** [comment]
Fixed with current version of Sprai 0.9.9.23
