### ISSUE TITLE
Organelle_PBA dies in Step 5 "Evaluating repetitive regions"

### ISSUE THREAD

**Issue by diriano** [aubombarely/Organelle_PBA#4]
Using the test data, Organelle_PBa dies in step 5 with the following message:

============================================================
 5) Evaluating repetitive regions (Mon Oct  2 11:10:10 BRT 2017)
============================================================

	5.1- Running BlasR re-mapping.

	5.2- Running samtools view (Sam to Bam).

	5.3- Sorting bam file.

Use of uninitialized value $getmap01count in scalar chomp at /data1/bioinfo/Organelle_PBA/OrganelleRef_PBA line 1345.
	5.4- Calculating coverage.

Illegal division by zero at /data1/bioinfo/Organelle_PBA/OrganelleRef_PBA line 2267.

**Comment by agroppi** [comment]
@diriano 
I think I have found the bug see #5 
But since it's not possible to resume the pipeline at this step we have to wait ...

**Comment by agroppi** [comment]
Unfortunatly, my modification didn't solved the bug ...
Waiting for a solution from @aubombarely

**Comment by aubombarely** [comment]
I think that it fixed with the new Organelle_PBA version. Please check. Thanks.
