### ISSUE TITLE
Illegal division by zero at OrganelleRef_PBA line 2266 [STEP 5.4]

### ISSUE THREAD

**Issue by agroppi** [aubombarely/Organelle_PBA#5]
Organelle PBA run until the Step 5.4 : 

```
5) Evaluating repetitive regions (Wed Oct  4 07:31:39 CEST 2017)
============================================================

	5.1- Running BlasR re-mapping.

	5.2- Running samtools view (Sam to Bam).

	5.3- Sorting bam file.

Use of uninitialized value $getmap01count in scalar chomp at /home/ag/Organelle_PBA/OrganelleRef_PBA line 1344.
	5.4- Calculating coverage.

Illegal division by zero at /home/ag/Organelle_PBA/OrganelleRef_PBA line 2266.
```
Solution ?

Thanks

**Comment by agroppi** [comment]
I thinks I have found the bug : 
With bedtools 2.26.0

line 1365 : `my $bedgc01cmd = "$bedexe genomecov -d -ibam $bamout -g $gemsize";`

has to be modified  : `$bedexe genomeCoverageBed -d -ibam $bamout -g $gemsize";`

But It will be very useful to be able to to resume the pipeline at this step in order to avoid to repeat the previous steps (time consuming)

**Comment by agroppi** [comment]
same issue as #4

**Comment by agroppi** [comment]
Unfortunatly, my modification didn't solved the bug ...
Waiting for a solution from @aubombarely

**Comment by agroppi** [comment]
Many bugs were linked to the bad construction of command lines at the steps 5 and following
Here is a modified version of OrganelleRef_PBA who works until the end.
/!\ some lines are paths specific to our computing environment 
==> to be adapted

Hope this helps other users. 
[OrganelleRef_PBA_modified.zip](https://github.com/aubombarely/Organelle_PBA/files/1437241/OrganelleRef_PBA_modified.zip)

**Comment by aubombarely** [comment]
I think that it is fixed. It was a problem with the version of BlasR and Bedtools. The original BlasR version did not use X in the cigar line, but the new versions do it. Bedtools v2.19.0 or lower did not handle that. Closing the issue.
