### ISSUE TITLE
ERROR: Sprai/CA didnt produced an output 9-terminator. 

### ISSUE THREAD

**Issue by sanvva** [aubombarely/Organelle_PBA#8]
$ OrganelleRef_PBA -i artha_pacbioSRR1284093_c025k.fastq -r artha_refchl01_artha.fa -o artha_chl

############################################################
############################################################

============================================================
 0) Checking arguments (Mon Apr 16 11:18:32 CST 2018)
============================================================

	Input PacBio reads file: artha_pacbioSRR1284093_c025k.fastq
	Input type: fastq
	Output directory: artha_chl
	Organelle reference fasta file: artha_refchl01_artha.fa
		Organelle reference size: 154478 bp
		Repeat block size coverage detection: 1000
		Coverage ratio to define repeatitive region: 1.6
	Completeness fraction: 1.0
	Breaks overlap: 0
	Highest position to set up origin: 1
	Starting-End margin to check circularity: 10
	Overlap length to check circularity: 100
	Minimum BlasR alignment percentage: 5

	bedtools is available in the PATH (/usr/bin/bedtools)
	blasr is available in the PATH (/usr/bin/blasr)
	blastn is available in the PATH (/home/hzs/bin/ncbi-blast-2.7.1+/bin/blastn)
	makeblastdb is available in the PATH (/home/hzs/bin/ncbi-blast-2.7.1+/bin/makeblastdb)
	runCA is available in the PATH (/home/hzs/bin/wgs/Linux-amd64/bin/runCA)
	pacBioToCA is available in the PATH (/home/hzs/bin/wgs/Linux-amd64/bin/pacBioToCA)
	PBcR is available in the PATH (/home/hzs/bin/wgs/Linux-amd64/bin/PBcR)
	samtools is available in the PATH (/usr/bin/samtools)
	ezez_vx1.pl is available in the PATH (/home/hzs/bin/sprai/bin/ezez_vx1.pl)
	ezez4qsub_vx1.pl is available in the PATH (/home/hzs/bin/sprai/bin/ezez4qsub_vx1.pl)
	bfmt72s is available in the PATH (/home/hzs/bin/sprai/bin/bfmt72s)
	m52bfmt7 is available in the PATH (/home/hzs/bin/sprai/bin/m52bfmt7)
	myrealigner is available in the PATH (/home/hzs/bin/sprai/bin/myrealigner)
	nss2v_v3 is available in the PATH (/home/hzs/bin/sprai/bin/nss2v_v3)
	fa2fq.pl is available in the PATH (/home/hzs/bin/sprai/bin/fa2fq.pl)
	check_circularity.pl is available in the PATH (/home/hzs/bin/sprai/bin/check_circularity.pl)
	dfq2fq_v2.pl is available in the PATH (/home/hzs/bin/sprai/bin/dfq2fq_v2.pl)
	SSPACE-LongRead.pl is available in the PATH (/home/hzs/bin/SSPACE-LongRead_v1-1/SSPACE-LongRead.pl)

============================================================
 1) Running BlasR (Mon Apr 16 11:18:33 CST 2018)
============================================================

	1.1- Converting Fastq to Fasta.
	      Using Seqtk to convert Fastq to Fasta.
	     Input PacBio read file contains 24903 reads

	1.2- Running BlasR mapping.

	1.3- Processing the BlasR output.
	      1263 reads (13909469 bp) will be selected
	      Estimated depth (reference based): 90 X.

	1.4- Selecting reads from the fastq file
	      Using Seqtk to select reads from fastq.

============================================================
 2) Running assembly (Sprai) (Mon Apr 16 11:28:07 CST 2018)
============================================================

	2.1- Creating the ec.spec file for Sprai.

	2.2- Creating the pbasm.spec file for Sprai.

	2.3- Running Sprai.

	2.3- Analyzing the results
ERROR: Sprai/CA didnt produced an output 9-terminator. Check log.

**Comment by sanvva** [comment]
----------------------------------------START Mon Apr 16 11:28:07 2018
/home/hzs/bin/wgs/Linux-amd64/bin/gatekeeper  -o /home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_20180416_112807//CA/asm_CA_01_20180416_112807.gkpStore.BUILDING  -T  -F  /home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_20180416_112807//CA/c01.fin.top20x.frg > /home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_20180416_112807//CA/asm_CA_01_20180416_112807.gkpStore.err 2>&1
----------------------------------------END Mon Apr 16 11:28:08 2018 (1 seconds)
ERROR: Failed with signal ABRT (6)
================================================================================

runCA failed.

----------------------------------------
Stack trace:

 at /home/hzs/bin/wgs/Linux-amd64/bin//runCA line 1628.
	main::caFailure("gatekeeper failed", "/home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_2018041"...) called at /home/hzs/bin/wgs/Linux-amd64/bin//runCA line 1957
	main::preoverlap("/home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_2018041"...) called at /home/hzs/bin/wgs/Linux-amd64/bin//runCA line 6250

----------------------------------------
Last few lines of the relevant log file (/home/hzs/bin/Organelle_PBA/testdata/artha_chl/result_20180416_112807//CA/asm_CA_01_20180416_112807.gkpStore.err):


----------------------------------------
Failure message:

gatekeeper failed

**Comment by amit4mchiba** [comment]
Hi Sanvva,

Did you got solution for the problem that you metioned. I have got same problem and not being able to solve. Please let me know things that you tried and things that helped you to make it work.

best regards
Amit

**Comment by sanvva** [comment]
@amit4mchiba Sorry, I got help from our serve administrator to install the software on the HPC instead of on my desktop PC. I don't know how he worked it out.
