### ISSUE TITLE
how to get SSPACE-Long?

### ISSUE THREAD

**Issue by rahmanYI** [aubombarely/Organelle_PBA#9]

**Comment by rahmanYI** [comment]
SSPACE-Long==SSPACE-LongRead?

**Comment by zhavgyating** [comment]
https://www.baseclear.com/services/bioinformatics/basetools/sspace-longread/

**Comment by aubombarely** [comment]
Thanks

**Comment by xizhesun** [comment]
Dear all,

Anyone could share the SSPACE-LongRead? The website has lost. 

Thank you.
